
<div id="termsPage" class=" overflow-y-auto  top-0 w-full flex flex-col justify-center px-24">
    <h1 class="font-bold">Terms & Conditions</h1>
    THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF THE INFORMATION
    TECHNOLOGY, ACT, 2000 AND RULES MADE THEREUNDER. THIS ELECTRONIC
    RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE
    ANY PHYSICAL OR DIGITAL SIGNATURES. THESE TERMS & CONDITIONS WERE
    UPDATED ON 29th June 2020 (hereinafter referred to as the “Agreement”/ “Terms of Use”)
    <h2 class="font-bold">1. INTRODUCTION ON THE SCOPE OF THE AGREEMENT</h2>
    TERMS AND CONDITIONS CONSTITUTE LEGAL CONTRACT. The terms stated
    herein including any additional guidelines and/or future modifications to this Agreement read
    together with the Privacy Policy, available at www.aeps.kadamba.biz shall constitute a legal
    contract between any person utilizing KADAMBA’s services (“User”) of the one part, and
    KADAMBA INTRAC PRIVATE LIMITED (“KADAMBA”/“Company”) having its
    Corporate office at #740, 10th main, 4th lock, Jayanagar, Bangalore – 560011 of the other
    part (collectively referred to as “Parties” and singularly referred to as “Party”).
    ACCEPTANCE OF T&Cs. By using, browsing, accessing, registering or
    accessing www.aeps.kadamba.biz or any mobile application developed by KADAMBA
    (“Site”), or availing any service rendered by KADAMBA, a User fully, absolutely and
    unequivocally agrees to comply with and abide by the Agreement.
    ELIGIBILITY : KADAMBA’s services are open only to persons of 18 years of age and above
    who have a valid e-mail address and mobile phone number. Users who have been previously
    suspended or removed from availing any service by KADAMBA shall not be eligible to avail
    services from KADAMBA. Users shall not impersonate any person or entity, or falsely state
    or otherwise misrepresent identity, age or affiliation with any person or entity. If you are below
    18 years of age, please exit the Site.
    APPLICABILITY. The terms of this Agreement shall be applicable to Users, Business
    Partners, Alliance Partners and Applicable Controlled Entities, as set forth in this Agreement.
    This Agreement shall be deemed to be incorporated in the Applicable Agreement. Any
    reference to the “Agreement” shall include a reference to the Applicable Agreement and any
    reference to “Applicable Agreement” shall include a reference to this Agreement.
    INCONSISTENCY. Notwithstanding anything contained herein, Applicable Agreement shall
    prevail over this Agreement in case of any inconsistency.
    <h2 class="font-bold">2. DEFINITIONS AND INTERPRETATION</h2>
    In this Agreement, unless the contrary intention appears and/or the context otherwise requires,
    capitalized terms defined by: (i) inclusion in quotation and/or parenthesis have the meanings
    so ascribed; and (ii) the following terms shall have the meanings assigned to them herein below:
    “Alliance Partners” are individuals/sole-proprietorships/companies/LLP’s etc who have
    entered into a service agreement with KADAMBA for offering KADAMBA’s products and
    services through web/mobile/API or through any channel whose particulars are listed in Clause
    1 of the service agreement with Alliance Partners.
    “Applicable Agreement” refers to service agreement in relation to Business Partners and
    Alliance Partners.
    “Applicable Controlled Entity” collectively refers to (i) Sub-Partners appointed by Business
    Partners, and the Alliance Partners.
    “Applicable Law” includes all applicable Indian statutes, enactments, acts of the state
    legislature or parliament, laws, ordinances, rules, bye-laws, regulations, notifications,
    guidelines, directions, directives and orders of any governmental authority, statutory authority,
    board, recognized stock exchange, as may be applicable including but not limited to Guidelines
    on Managing Risks and Code of Conduct in Outsourcing of Financial Services by Banks,
    Business Correspondent Guidelines issued by RBI from time to time, Payment & Settlement
    Systems Act, 2007 and rules made thereunder, Policy Guidelines on Issuance and operation of
    Pre-paid Payment Instruments in India.
    “Business Partners” are firms who have entered into a service agreement with KADAMBA
    whose particulars are listed in Clause 1 of the service agreement.
    “Confidential Information” means and includes the Intellectual Property and any and all
    business, technical and financial information of KADAMBA or of any of its affiliates that is
    related to any of the arrangements contemplated in this Agreement or any other agreement in
    which this Agreement is incorporated by reference or otherwise disclosed by KADAMBA to
    the User any information which relates to its financial and/or business operations, including
    but not limited to, specifications, models, merchant lists/information samples, reports,
    forecasts, current or historical data, computer programs or documentation and all other
    technical, financial or business data, information related to its internal management, customers,
    products, services, anticipated products/services, processes, financial condition, employees,
    merchants, Intellectual Property, marketing strategies, experimental work, trade secrets,
    business plans, business proposals, customer contract terms and conditions,
    compensation/commission/ service charges payable to the User, and other valuable
    confidential information and materials that are customarily treated as confidential or
    proprietary, whether or not specifically identified as confidential or proprietary.
    “Customers” shall mean persons, including all body corporate, partnerships, limited liability
    partnerships, who are availing services, either as a consumer or otherwise, rendered by a service
    provider through the User using KADAMBA’s products or services.
    “Credit” shall mean the payment made by the Business Partner/Alliance Partner to the
    Company to carry out transactions through the KADAMBA platform.
    “Effective Date” shall mean the date of activation of the account of the User on KADAMBA’s
    portal.
    “KADAMBA Platform” shall mean and include, the platforms (website, mobile app, others)
    of KADAMBA that the User accesses for registration and further for transacting, including all
    contents, services, and technology offered through the Platform.
    “Intellectual Property” shall mean all intellectual property used for the purpose of or in
    association with or in relation to the performance of this Agreement and Applicable
    Agreement, and includes without limitation, (a) Software, operating manuals, software code,
    program, instructions, specifications, processes, input methods, data or information used in
    relation to, or in association with, or for the operation of the software installed by KADAMBA,
    (b) the trademarks, service marks, trade names, business names, logos, symbols, styles, colour
    combinations used by KADAMBA during the course of its business and all depictions,
    derivations and representations thereof, (c) all promotional material including without
    limitation, advertisements, literature, graphics, images, content and the ‘look and feel’ of all of
    the above, (d) all information, data or material in whatever form, whether tangible or not,
    provided by KADAMBA to the User during the course of Applicable Agreement; and (e) all
    techniques, formulae, patterns, compilations, processes, inventions, practices, methodology,
    techniques, improvement, utility model, procedures, designs, skills, technical information,
    notes, experimental results, service techniques, samples, specifications of the products or
    services, labeling specifications, rights on software, and any other knowledge or know-how of
    any nature whatsoever.
    “Merchants” shall mean individuals and/or entities registered on KADAMBA platform and/or
    appointed by KADAMBA and/or for discharging functions prescribed under these terms &
    conditions and/or includes Business Partners, Alliance Partners, etc.
    “Products” shall mean products developed by KADAMBA including products permitting
    electronic top-ups, utility bill payments, travel bookings, delivery of various financial products,
    other value-added services using various devices like ATMs, POS, Mobile Apps, Internet and
    any other products available on KADAMBA platform from time to time.
    “Service Provider” shall mean any entity with which KADAMBA has, directly or indirectly,
    executed an agreement for facilitating Transactions between such entity and its Customers.
    “Software” shall include custom-built software that is owned by KADAMBA, or software that
    has been licensed from third party suppliers by KADAMBA and in relation to which
    KADAMBA has obtained the right to sub-license from such third party suppliers.
    “Sub-Partners” shall mean individuals and/or entities appointed by the merchants on whose
    premises/outlets/website the Products shall be sold to the Customers, for and on behalf of the
    Service Providers, to facilitate completion of Transactions initiated by such Customers,
    through the merchants.
    “Transactions” shall mean and include transactions taking place between a Service Provider
    and its Customers including, but not limited to, electronic top-ups for various services, utility
    bill payments, delivery of financial products and other services of a like nature provided by the
    Service Provider through KADAMBA’s Products.
    “Users” shall include individuals, Business Partner, and Alliance Partner, unless the context
    provides otherwise or if the context in which the term “User” has been used is inapplicable to
    such individual, Business Partner or Alliance Partner.
    <h2 class="font-bold">3. GENERAL TERMS AND CONDITIONS</h2>
    INFORMATION SUPPLIED TO INSTANTPAY. Users agree that the information
    provided by the Users to KADAMBA on registration and at all other times, including payment,
    is true, accurate, current, and complete.
    SECURITY OF ACCOUNT. Users’ mobile number and email identify a Users’ account with
    KADAMBA through which KADAMBA services are dispensed (“Account’). KADAMBA
    encourages Users to choose a strong password to protect their Account. It is advised that users
    do not share their password with anyone or write it down. KADAMBA never, under any
    circumstances, asks for an Account’s password. If a User has any reason to believe that his
    Account is no longer secure, then the User shall immediately notify KADAMBA and
    indemnify KADAMBA from any liabilities that may arise from the misuse of such a User’s
    Account.
    PRIVACY POLICY. All information collected from a User pursuant to the provision of
    KADAMBA’s services, and information collected by Alliance Partner, Business Partners, SubPartners and Merchants during the performance of this Agreement or Applicable Agreement,
    is subject to KADAMBA’s Privacy Policy.
    <h2 class="font-bold">RECLAIMING INACTIVE ACCOUNTS.</h2> If an Account is found to be overly inactive, the
    Account may be reclaimed by KADAMBA without providing notice to the concerned User.
    An Account is considered as inactive if the concerned User is not signing in and/or has not
    done any transactions for more than 6 consecutive months from the Account.
    THIRD PARTY SITES, PRODUCTS AND SERVICES. KADAMBA’s services and/or the
    Site may include links or references to other web sites or services solely for the Users’
    convenience (“Reference Sites”). KADAMBA does not endorse any such Reference Sites or
    the information, materials, products, or services contained on or accessible through Reference
    Sites. Correspondence or business dealings between Users and concerned Reference Sites are
    solely between such User and the concerned Reference Site. Access and use of Reference Sites,
    including the information, materials, products, and services on or available through Reference
    Sites is solely at concerned User’s own risk.
    <h2 class="font-bold">BILLING AND PAYMENT.</h2> All payments made by Users directly to KADAMBA, shall be
    made in the manner and in the quantum detailed on the User’s Account at KADAMBA
    Platform. Users may be notified by KADAMBA regarding any change in the quantum of
    payments to be made to KADAMBA and the manner of disbursement of such payments;
    however Users are advised to regularly update themselves of KADAMBA’s billing and
    payment policy by regularly visiting the Site. KADAMBA shall solely decide on the payments
    to be provided to User and may amend the payment structure at any time without any prior
    notice to the User. However, after any such amendment, the detailed payment structure will be
    made available to the User and be effective immediately. Credit maintained by the Users with
    KADAMBA shall be non-interest bearing and shall be forfeited by KADAMBA if found lying
    unused for more than 365 days. The User shall keep enough Credit with KADAMBA to avoid
    decline of transactions on the KADAMBA Platform.
    SALES. All sales of KADAMBA’s services are final with no refund or exchange permitted.
    Users are responsible for details provided leading to purchase of services. If KADAMBA does
    not deliver service within 24 hours of money being charged to a User’s payment account
    through a transaction on the Site, the User may inform KADAMBA by sending an e-mail to
    KADAMBA’s customer services e-mail address mentioned on the Contact Us page.
    KADAMBA shall investigate the case and if it is found that money was indeed charged to
    User’s Payment Account without delivery of the service then User may be refunded the money
    within 15 working days from the receipt of his e-mail.
    <h2 class="font-bold">LIMITATION OF LIABILITY.</h2> In no event will KADAMBA or its directors, agents,
    officers, or employees be liable to a User for any special, indirect, incidental, consequential,
    punitive, or exemplary damages (including without limitation lost business opportunities, lost
    revenues, or loss of anticipated profits or any other pecuniary or non-pecuniary loss or damage
    of any nature whatsoever) of any kind arising out of or relating to (i) this Agreement or any
    other agreement entered by a User with KADAMBA, (ii) KADAMBA’s services, the Site or
    any Reference site, or (iii) User’s use or inability to use KADAMBA’s services, the Site or any
    Reference Sites, even if KADAMBA or a KADAMBA authorized representative has advised
    of the possibility of such damages, (iv) unauthorized access to or alterations of transmissions
    or data, any material or data sent or received or not sent or received, (v) any transactions entered
    into by any third person or conduct of any other third party or any infringement of another’s
    rights, (vi) the use of counterfeit or stolen cards, or stolen devices, or (vii) fraudulent electronic
    transactions. It shall be at the sole discretion of KADAMBA to reverse any transaction subject
    to approval of the concerned Service Provider. Notwithstanding the above, if any court of law
    finds that KADAMBA or its directors, officers, or employees, are liable to indemnify a
    concerned User despite the existence of this Clause 3.8, such liability shall not exceed the
    amount paid by the concerned User, if any, for using the portion of the KADAMBA’s services
    or the Site giving rise to the cause of action. Users acknowledge and agree that KADAMBA
    has offered its products and services, set its prices, and entered into this Agreement and
    Applicable Agreement in reliance upon the warranty, disclaimers, and the limitations of
    liability set forth herein. Users acknowledge that the warranty, disclaimers, and limitations of
    liability set forth herein reflect a reasonable and fair allocation of risk between Users and
    KADAMBA, and that the warranty, disclaimers, and limitations of liability set forth herein
    form an essential basis of the bargain between Users and KADAMBA. KADAMBA would not
    be able to provide the services to Users on an economically reasonable basis without these
    limitation.
    <h2 class="font-bold">USER’S REPRESENTATIONS AND WARRANTIES.</h2> The User represents and warrants
    that:it has had a full and adequate opportunity to read and review the Applicable Agreement
    and has had sufficient time to evaluate and investigate the provision of services under the
    Applicable Agreement and the financial requirements and risk associated with the same,
    it has the requisite capital to set up and maintain the infrastructure as required under the
    Applicable Agreement, neither the execution of the Applicable Agreement nor the performance
    of the User’s obligations under the Applicable Agreement will result in a violation or breach
    of any other agreement by which the User is bound,neither the User nor any of the User’s
    employees or agents is under any pre-existing obligation in conflict or in any way inconsistent
    with the provisions of the Agreement or Applicable Agreement,it has the right to disclose or
    use all ideas, and other information, if any, which the User has gained from third parties, and
    which the User discloses to KADAMBA in the course of performance of the Agreement or
    Applicable Agreement, without liability to such third parties, KADAMBA has a right to inspect
    User’s business premises that are related to the provision of services under the Agreement or
    Applicable Agreement, and to monitor continued and ongoing compliance of the Applicable
    Agreement,it shall immediately intimate KADAMBA of any violation or potential violation of
    this Agreement by any Applicable Controlled Entity, or of other circumstances that may cause
    damage to the goodwill and reputation of KADAMBA,it shall maintain accurate and proper
    accounts of all transactions between Applicable Controlled Entity and itself in relation to
    discharge of duties by the Applicable Controlled Entity under the Applicable Agreement,it
    shall provide periodic reports of business operations with respect to the services rendered under
    the Applicable Agreement to the sales executive assigned by KADAMBA to the User,it shall
    observe proper ethics and transparency in all its actions in the course of discharge of duties
    under the Applicable Agreement and shall not, in any circumstances, take any action or make
    any statement that may mislead any Applicable Controlled Entity/customer or prospective
    Applicable Controlled Entity /customer of KADAMBA it shall make all efforts to settle any
    disputes that may arise between Applicable Controlled Entity, or between the Applicable
    Controlled Entity and the consumers amicably and in the event, any such dispute is referred to
    a consumer forum or other competent authority, shall provide all assistance in the settlement
    of the dispute,it shall bear all costs and expenses for traveling, promotional activities and other
    similar out-of-pocket expenses incurred in the performance of its duties under the Applicable
    Agreement,it will not allow the sale of any products and/or provision of any services which are
    specifically restricted by KADAMBA,it is a one-point contact for all its Applicable Controlled
    Entities and shall be solely responsible for any fraudulent acts of the Applicable Controlled
    Entities,it has complete control over its Applicable Controlled Entities and that KADAMBA
    will not be responsible to entertain any complaints/queries received from any Applicable
    Controlled Entities appointed by the User,it shall comply with all its obligations pursuant to
    the Applicable Agreement and ensure that all payments due from it to KADAMBA are paid in
    a timely manner in accordance with the Applicable Agreement,it shall be responsible to obtain
    any and all consents and approvals that are required from regulatory or governmental
    authorities, including any consent from Customers required to transfer data to the User and/or
    the KADAMBA Platform, as the case may be, in accordance with Applicable Law,it shall
    ensure regular and timely payment and deposit of all taxes, duties and other levies as applicable
    from time to time with the relevant authorities,All costs associated with purchasing of software
    licenses and hardware (if any) are to be absolutely and unconditionally borne by the User,it
    shall be solely responsible for and hereby undertakes to strictly comply with Privacy Policy,
    and Applicable Law having jurisdiction in any manner whatsoever in connection with
    discharge of its duties under the Applicable Agreement, including but not limited to data
    protection, security, piracy, and directions issued by the Reserve Bank of India relating to
    payment data, and shall obtain and maintain in full force and effect all registrations required
    under Applicable Law for the operation of the business in terms of the Applicable Agreement,
    andit has full power and authority to enter into the Applicable Agreement and to take any action
    and execute any documents required by the terms hereof and this Applicable Agreement has
    been duly authorized, duly and validly executed and delivered, and constitutes a legal, valid,
    and binding obligation, enforceable in accordance with the terms hereof; and the persons
    executing the Applicable Agreement on its behalf are duly empowered and authorized to
    execute the Applicable Agreement and to perform all its obligations in accordance with the
    terms herein it shall not access (or attempt to access) the website and the Products by any means
    other than through the interface that is provided by KADAMBA. It shall not use any deep-link,
    page scrape, robot, spider or other automatic device, program, algorithm or methodology, or
    any similar or equivalent manual process, to access, acquire, copy or monitor any portion of
    the KADAMBA Platform, or in any way reproduce or circumvent the navigational structure or
    presentation of the platform, without KADAMBA’s express prior written consent.
    it shall not attempt to gain unauthorized access to any portion or feature of the Platform, or any
    other systems or networks connected to the Platform or to any server, computer, network, or to
    any of the services offered on or through the Platform, by hacking, password "mining" or any
    other illegitimate means.
    <h2 class="font-bold">INDEMNIFICATION.</h2>
    (1) User agrees to indemnify, save, and hold KADAMBA, its affiliates, contractors, employees,
    officers, directors, agents and its third party suppliers, licensors, and partners harmless from
    any and all claims, demands, actions, suits which may be threatened or brought against
    KADAMBA, and also against all losses, damages, liabilities, costs, charges and expenses,
    including without limitation, legal fees and expenses arising out of or related to:
    Users’ use or misuse of KADAMBA’s services or of the Site/application, any violation by the
    User of this Agreement or Applicable Agreement, any breach of representations, warranties
    and covenants made by the User in this Agreement, or Applicable Agreement, any claim or
    legal notice or quasi-legal proceedings to which KADAMBA may be required to become party
    or to which KADAMBA may be subjected by any person including any governmental
    authority, by reason of breach of any Applicable Law, due to failure of a User to obtain any
    required statutory or regulatory approval necessary for the performance of its obligations in the
    Applicable Agreement with KADAMBA, all liability, claims, damages, costs, expenses
    suffered or incurred by KADAMBA as a result of any act or violation of the Business Partner
    under Section 269ST of the Income Tax Act, 1961 while acting as collection agent of the
    Company.
    (2) KADAMBA reserves the right, at User’s expense, to assume the exclusive defence and
    control of any matter, including rights to settle, for which concerned User is required to
    indemnify KADAMBA. User agrees to cooperate with KADAMBA’s defence and settlement
    of these claims. KADAMBA will use reasonable efforts to notify concerned User of any claim,
    action, or proceeding brought by a third party that is subject to the foregoing indemnification
    upon becoming aware of it.
    DISCLAIMER. To the fullest extent permissible pursuant to Applicable Law, KADAMBA
    and its officers, directors, employees, and agents disclaim all warranties, express or implied,
    including, but not limited to, implied warranties of merchantability, fitness for a particular
    purpose, and non-infringement of proprietary rights. No advice or information, whether oral or
    written, obtained by a User from KADAMBA or through KADAMBA’s services or the Site
    will create any warranty not expressly stated herein. KADAMBA does not authorize anyone
    to make any warranty on its behalf and Users should not rely on any such statement. Users
    acknowledge that KADAMBA is a reseller and is not liable for any third-party seller’s
    obligations. It is the User’s responsibility to evaluate the accuracy, completeness and
    usefulness of all opinions, advice, merchandise and other information provided through the
    Site or on the Internet generally. KADAMBA does not warrant that its services will be
    uninterrupted, or free of errors, viruses or other harmful components and that any of the
    foregoing defects will be corrected. KADAMBA’s services and the Site and any data,
    information, third party software, Reference Sites, or software made available in conjunction
    with or through its services and the Site are provided on an “as is” and “as available”, “with all
    faults” basis and without warranties or representations of any kind either express or implied.
    KADAMBA and its third party suppliers, licensors, and partners do not warrant or make any
    representations regarding the use or the results of the use of KADAMBA’s services, the Site
    or any Reference Sites in terms of correctness, accuracy, reliability, or otherwise.
    INTELLECTUAL PROPERTY. KADAMBA’s services and the Site are owned and
    operated by KADAMBA and/or third-party licensors. The visual interfaces, graphics, design,
    compilation, information, computer code (including source code and object code), products,
    software, services, and all other elements of KADAMBA’s services and the Site provided by
    KADAMBA (the “Materials”) are protected by Applicable Law. As between User and
    KADAMBA, all Materials and KADAMBA’s Intellectual Property are the property of
    KADAMBA and/or third-party licensors or suppliers. User agrees not to remove, obscure, or
    alter KADAMBA or any third party's copyright, patent, trademark, or other proprietary rights
    notices affixed to or contained within or accessed in conjunction with or through KADAMBA’s
    services. Except as expressly authorized by KADAMBA, the User agrees not to sell, license,
    distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create
    derivative works from, or otherwise make unauthorized use of the Materials or KADAMBA’s
    Intellectual Property. Parties do not accrue any rights or interest in the other Party’s Intellectual
    Property and use of any Intellectual Property by either User or KADAMBA shall be strictly in
    for the fulfilment of and in compliance with the terms of the agreement between such User and
    KADAMBA. Parties undertake that they shall not, nor will they allow others to, reverse
    engineer or disassemble any parts of the other’s Intellectual Property. If Users’ have comments
    regarding the KADAMBA’s services and the Site or ideas on how to improve it, please contact
    our Helpdesk. Please note that by doing so, concerned Users hereby irrevocably assign to
    KADAMBA, and shall assign to KADAMBA, all right, title and interest in and to all ideas and
    suggestions and any and all worldwide intellectual property rights associated therewith.
    Concerned User agrees to perform such acts and execute such documents as may be reasonably
    necessary to perfect the foregoing rights.
    INTELLECTUAL PROPERTY LICENSE BY ALLIANCE PARTNER. Alliance Partner
    grants a non-exclusive license to KADAMBA to use Alliance Partner’s name, trademark, and
    logo in any marketing or promotional activities undertaken by KADAMBA. Notwithstanding
    anything contained herein, KADAMBA shall be under no obligation to advertise, market, or
    promote Alliance Partner or Alliance Partner’s Intellectual Property.
    USE OF INTELLECTUAL PROPERTY. The user undertakes that: it shall use the
    Intellectual Property solely for the discharge of its duties under the Applicable Agreement,
    it shall use Intellectual Property of KADAMBA only in the form and manner stipulated by
    KADAMBA, it shall seek prior written consent from KADAMBA for use of KADAMBA’s
    Intellectual Property which is not previously provided for by KADAMBA, it shall bring to
    KADAMBA’s notice all cases concerning KADAMBA’s Intellectual Property’s (a)
    infringement, (b) passing off, (c) registration or (d) attempted registration, it shall render to
    KADAMBA all assistance in connection with any matter pertaining to the protection of
    KADAMBA’s Intellectual Property whether in courts, before administrative agencies, or
    otherwise, it shall not take any action which shall or may impair KADAMBA’s right, title or
    interest in the Intellectual Property, or create any right, title or interest therein or thereto,
    adverse to that of KADAMBA, it shall not use or permit to be used the Intellectual Property
    by any unauthorized person, and it shall not misuse the Intellectual Property or use it together
    with any other mark or marks.
    MODIFICATION. KADAMBA reserves the right to change, modify, add, or remove the
    terms of this Agreement, either in its entirety or a part thereof (each, a “change”) at any time
    by posting a notification to the Site or otherwise communicating the notification to Users. The
    changes will become effective, and shall be deemed accepted by Users, 24 hours after the initial
    posting and shall apply immediately on a going-forward basis with respect to payment
    transactions initiated after the posting date. If Users do not agree with any such modification,
    Users sole and exclusive remedy is to terminate their use of the Services.
    CONFIDENTIALITY. Parties shall keep Confidential Information as confidential. Each
    Party confirms that it shall protect Confidential Information with such security, confidentiality,
    and degree of utmost care as it would prudently apply to its own confidential information and
    use it solely in connection with the transaction to which the Confidential Information relates.
    Both Parties acknowledge and agree that they are aware of the sensitivity & secrecy involved
    in keeping the customer data/information and transaction records and shall ensure that neither
    any of the parties nor their employees, directors, etc will do any act to violate the same.
    Notwithstanding anything contained in this Clause 3.16, Confidential Information shall
    exclude any information: which is already in the possession of the receiving Party and not
    subject to any other duty of confidentiality, that is at the date hereof, or subsequently becomes,
    public otherwise than by reason of a breach by the receiving party of the terms of this
    Agreement, Information that becomes legally available to the receiving Party and/or its
    affiliates or professional advisors on a non-confidential basis from any third party, the
    disclosure of which does not, to the knowledge of that Party, violate any contractual or legal
    obligation which such third party has to the other Party with respect to such information, and
    Information that is independently acquired or developed by the receiving Party and/or its
    affiliates or professional advisors.
    <h2 class="font-bold">DISCLOSURE OF CONFIDENTIAL INFORMATION.</h2> Each Party hereby agrees that it
    shall not disclose any Confidential Information received by it without the prior written consent
    of the other Party to any third party at any time. Provided, however, that either Party may make
    the following disclosures for which no consent shall be required from the other Party:
    Disclosures to its directors, officers, employees, affiliates/subsidiaries/group/holding
    companies, third-party service providers and any employees thereof that it reasonably
    determines need to receive the Confidential Information;
    Disclosures to its legal and other professional advisers, instructed by it that it reasonably
    determines to need to receive the Confidential Information; or
    Disclosures to any person to whom it is required by law or any applicable regulatory,
    supervisory, judicial or governmental order, to disclose such information, or at the request of
    any regulatory or supervisory or judicial or government authority.
    NON SOLICITATION OF EMPLOYEES. The Parties agree not to solicit or employ staff
    from each other’s organizations during the term of this Agreement and for 12 months
    immediately following the termination of the Agreement.
    NON SOLICITATION OF CLIENTS. During the term of this Agreement, the User shall
    not, either directly or indirectly, solicit, cause in any part of knowingly encourage any existing
    or potential clients or customers of KADAMBA to cease doing business or not to do business,
    in whole or in part with KADAMBA, or solicit, cause in any part or knowingly encourage an
    existing or potential clients or customers of KADAMBA to do business with any person other
    than KADAMBA, or associate with any prospective clients or customers while they continue
    to be clients or customers of KADAMBA.
    NON-COMPETE ON BUSINESS PARTNER. Business Partner agrees that during the Term
    and for a period of one (1) year thereafter, it shall not, directly or indirectly, through its
    employees, affiliates or relatives or in a firm where the Business Partner or any relative or
    nominee of the Business Partner is a partner, or in any company where the Business Partner or
    any relative or nominee of the Business Partner is a director or shareholder, without the prior
    written consent of KADAMBA: (i) be appointed as a Business Partner for any other person or
    legal entity which is carrying on a business similar to or in competition with any business
    carried by KADAMBA at the relevant time, whether in India or abroad, or (ii) engage in any
    business that is similar to or in competition with any business carried on by KADAMBA at the
    relevant time.
    <h2 class="font-bold">COUNTERPARTS.</h2> The Applicable Agreement may be signed in two (2) or more
    counterparts and each executed version or an electronic copy thereof shall be deemed an
    original and which shall, singly or together, constitute one agreement.
    TERM. This Agreement and Applicable Agreement shall come into force from the Effective
    Date and remain valid in perpetuity, unless terminated by KADAMBA by giving to the User,
    a prior written notice of at least 90 days (“Term”).
    <h2 class="font-bold">TERMINATION.</h2> This Agreement and Applicable Agreement may be terminated in
    accordance with the clauses below:
    KADAMBA shall be entitled to terminate this Agreement and Applicable Agreement by
    serving a written notice of thirty (30) days to the User in the following circumstances: (a) the
    User commits any breach of any of the provisions of this Agreement or Applicable Agreement
    and, in the case of a breach capable of remedy, fails to remedy the same within thirty (30) days
    after receipt of a written notice giving full particulars of the breach and requiring it to be
    remedied; (b) if, in KADAMBA’s opinion, the User is not a fit person/entity to carry out the
    obligations imposed on the User under the Applicable Agreement; (c) if the User fails to
    achieve the targets as may be communicated by KADAMBA from time to time.
    On the occurrence of the User becoming subject of a voluntary petition in bankruptcy or any
    voluntary proceeding relating to insolvency, receivership, liquidation, or composition for the
    benefit of creditors.
    KADAMBA may terminate the Agreement and Applicable Agreement without notice
    provided: (a) if, by the acts or default of the User, KADAMBA suffers damage to its name and
    reputation; or (b) the Business Partner commits any breach of Confidentiality; or (c) upon the
    occurrence of force majeure under Clause 3.28 of this Agreement; or (d) there is a change in
    shareholding/control or management of the User; or (e) any event that would affect the ability
    of the User to perform its obligations under the Applicable Agreement occurs; or (f) any of the
    directors/partners/proprietors of the Business Partner are convicted of any criminal charge.
    in the event that KADAMBA gives notice that the Alliance Partner’s software or hardware is
    technically inadequate to support the Connectivity at any stage of development, and the
    Alliance Partner fails to cure such deficiency within 90 days after receiving notice to such
    effect, then KADAMBA shall be entitled to give notice of termination as provided,
    in the event KADAMBA is unable to get necessary permission / license from any Service
    Provider and any statutory authority and/or any of the Service Provider rescinds its contract
    with KADAMBA and/or the sale of Products slips down due to any defective service,
    negligence or omission on part of the User, KADAMBA shall have the right to rescind the
    Agreement by giving 15 days’ notice to the User and the rescission shall take effect after expiry
    of the stipulated period of 15 days. Provided that unless otherwise specified by KADAMBA in
    its notice, any termination of this Agreement, on account of rescission of an existing contract
    with any Service Provider, shall be effective only in relation to Transactions pertaining to such
    Service Provider and the Agreement shall continue to remain in force between the Parties in
    respect of other Service Providers.
    CONSEQUENCES OF TERMINATION. The Parties shall adhere to the following clauses
    immediately upon termination of this Agreement: Upon termination of the Agreement for any
    reason, KADAMBA may immediately disconnect the availability of Products from the
    KADAMBA Platform, including related services provided by the platform, and no further
    Transactions may be effected through the KADAMBA.
    Except as otherwise agreed upon between the Parties, any license to use Intellectual Property
    Products, of either Party which has been granted by such Party to the other, pursuant to this
    Agreement, shall stand automatically revoked with the termination of this Agreement by any
    Party. User shall immediately discontinue and cease to use the trademark, logo and other
    Intellectual Property provided by the Company and shall immediately hand over any and all
    copies of documentation of such Intellectual Property.
    Upon the termination of this Agreement, the concerned User shall return and surrender to
    KADAMBA any Confidential Information that comes into its possession during the course of
    its engagement by KADAMBA and shall not retain a copy thereof in any form whatsoever.
    User shall, with KADAMBA’s prior written consent, promptly destroy the Confidential
    Information in its possession (and any copies, extracts, and summaries thereof) and will provide
    KADAMBA with written certification of destruction.
    immediately return to KADAMBA originals and copies of any and all materials provided to
    the User pursuant to the Applicable Agreement, including publicity and marketing materials in
    its possession.
    provide remote access to KADAMBA to disable any software that KADAMBA had installed.
    remove all signboards, banners, glow sign boards of KADAMBA from its office and also all
    such material, which will indicate any association with KADAMBA.
    cease to promote, market or advertise KADAMBA or its products/services. the User shall grant
    KADAMBA, its employees or agents, access to its information technology systems for a period
    of thirty (30) days after termination.
    Notwithstanding the above, the User shall not, if so directed by KADAMBA discontinue
    discharging its duties under the Applicable Agreement during the notice period and shall
    continue discharging its duties as per the Applicable Agreement until indicated otherwise by
    KADAMBA.
    KADAMBA shall have the right, exercisable at its sole discretion, to appoint another User in
    its place. The User shall fully cooperate with such newly appointed User. Upon notice of
    termination from either party, the User shall ensure that during the notice period leading to the
    termination, all systems and procedures will be strictly adhered to and all customers handled
    properly. All inquiries from customers will be diverted to KADAMBA by the User.
    Subject as otherwise provided in this Agreement and to any rights or obligations that have
    accrued before termination, neither Party shall have any further obligation to the other under
    this Agreement. Any termination of this Agreement or Applicable Agreement shall be without
    prejudice to KADAMBA’s rights under law and equity.
    PROMOTION. The user shall promote the sale of KADAMBA’s products/services in
    accordance with the publicity and marketing guidelines issued by the KADAMBA from time
    to time. User shall only market/promote KADAMBA’s services as authorized by KADAMBA
    in writing in this behalf and shall not market/promote any other services that may potentially
    be provided by KADAMBA in the future unless otherwise authorized in writing. The user shall
    maintain stock and prepare MIS of the promotional material dispatched from KADAMBA and
    ensure that such material will be displayed in the Merchant outlets at prominent eye-level
    locations to promote the business at that outlet.
    <h2 class="font-bold">ARBITRATION.</h2> KADAMBA may elect to resolve any dispute, controversy or claim arising
    out of or relating to the Agreement or KADAMBA’s services by binding arbitration in
    accordance with the provisions of the Indian Arbitration & Conciliation Act, 1996. Any such
    dispute, controversy or claim shall be arbitrated on an individual basis and shall not be
    consolidated in any arbitration with any claim or controversy of any other party. KADAMBA
    shall nominate a sole arbitrator who shall preside over the arbitration proceedings between
    KADAMBA and concerned User. The arbitration shall be conducted in SIRSI 581401 India
    and judgment on the arbitration award may be entered in any court having jurisdiction thereof.
    Either KADAMBA or concerned User may seek any interim or preliminary relief from a court
    of competent jurisdiction in SIRSI 581401 , India, necessary to protect the rights or the
    property of concerned User or KADAMBA (or its agents, suppliers, and subcontractors),
    pending the completion of arbitration. Any arbitration shall be confidential, and concerned
    User, nor shall KADAMBA disclose the existence, content or results of any arbitration, except
    as may be required by law or for purposes of the arbitration award. All administrative fees and
    expenses of an arbitration will be divided equally between KADAMBA and concerned User.
    In all arbitrations, each party will bear the expense of its own lawyers and preparation. The
    language of the arbitration shall be English.
    GOVERNING LAW. This Agreement shall be governed by and construed in accordance with
    the laws of India, without regard to its conflict of law provisions and, subject to the arbitration
    provision in section 3.19, the exclusive jurisdiction of competent courts in SIRSI 581401,
    India.
    <h2 class="font-bold">FORCE MAJEURE.</h2> Neither Party shall be liable for failure to perform its obligations under
    this Agreement to the extent such failure is due to causes beyond its reasonable control. In the
    event of a force majeure, the Party unable to perform shall notify the other Party in writing of
    the events creating the force majeure and the performance obligations of the Parties will be
    extended by a period of time equal to the length of the delay caused by force majeure; provided
    that if any such delay exceeds ninety days, then following such ninety-day period, either party
    hereto may terminate the unperformed portions of this Agreement on ten days prior written
    notice to the other Party. For the purposes of this Agreement, force majeure events shall
    include, but not be limited to, acts of God, failures or disruptions, orders or restrictions, war or
    warlike conditions, hostilities, sanctions, mobilizations, blockades, embargoes, detentions,
    revolutions, riots, looting, strikes, stoppages of labor, lockouts or other labor troubles,
    earthquakes, fires or accidents.
    <h2 class="font-bold">RECORDS AND AUDIT.</h2> The Users shall maintain all statutory records as may be required
    from time to time to be maintained under the Applicable Law. Further, the Users shall maintain
    accurate books of accounts in relation to their engagement with KADAMBA, pursuant to
    service rendered by User pursuant to the Applicable Agreement, in accordance with standard
    accounting practices and shall have the same audited annually by an auditor of good standing
    and repute and shall forward copies of the audited accounts to KADAMBA annually or as and
    when required by KADAMBA. The user hereby permits the authorized personnel of the
    KADAMBA to enter and inspect all books, accounts, records, and materials in relation to the
    business operations related to the Applicable Agreement during normal business hours. During
    the term of Applicable Agreement and at any time within sixty (60) days after the termination
    of the Applicable Agreement, KADAMBA or its employee/representative/agent may, at its
    expense, carry out an audit to determine whether the User has properly complied with its
    obligations under the Applicable Agreement. In the event the results of such audit determine
    that the User has not complied with its obligations under the Applicable Agreement,
    KADAMBA shall intimate the User of such non performance or the non-observance and the
    Business Partner shall immediately comply with its obligations, or within such other period as
    may be specified by Company.
    <h2 class="font-bold">PUBLIC RELATIONS.</h2> Upon execution of the Applicable Agreement, Parties shall have the
    right to announce the cooperative arrangement as described in the Agreement, provided that all
    announcements must be approved in writing by both Parties and such approval shall not be
    unreasonably withheld.
    <h2 class="font-bold">SEVERABILITY.</h2> If any provision of this Agreement is held to be unlawful, void, invalid or
    otherwise unenforceable, then that provision will be limited or eliminated from this Agreement
    to the minimum extent required, and the remaining provisions will remain valid and
    enforceable.
    ASSIGNMENT. This Agreement and any rights granted hereunder may not be transferred or
    assigned by User without KADAMBA’s prior written consent but may be assigned by
    KADAMBA without restriction. Any assignment attempted to be made in violation of this
    provision shall be void and of no effect.
    <h2 class="font-bold">SURVIVAL.</h2> Clause 1.4, 2.1, 3.3, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.16, 3.17, 3.18, 3.19, 3.20,
    3.26, 3.27, 3.33 of this Agreement shall survive the termination or expiration as applied to
    transfers and relationship prior to such termination or expiration.
    HEADINGS. The heading references herein are for convenience purposes only, do not
    constitute a part of this Agreement, and will not be deemed to limit or affect any of the
    provisions hereof.
    <h2 class="font-bold">ENTIRE AGREEMENT.</h2> This is the entire agreement between Users and KADAMBA
    relating to the subject matter hereof and will not be modified except in writing, signed by both
    parties, or by a Change to this Agreement made by KADAMBA in accordance with the terms
    of this Agreement.
    <h2 class="font-bold">NOTICE.</h2> KADAMBA may provide Users with notices and communications by email, regular
    mail, or posts on the KADAMBA website, www.aeps.kadamba.biz or by any other reasonable
    means. Except as otherwise set forth herein, notice to KADAMBA must be sent by courier or
    registered post to Legal Department, KADAMBA INTRAC PRIVATE LIMITED, #740,
    10th Main, 4th Block, Jayanagar, Bangalore - 560011 India.
    <h2 class="font-bold">WAIVER.</h2> The failure of KADAMBA to exercise or enforce any right or provision of this
    Agreement will not constitute a waiver of such right or provision. Any waiver of any provision
    of this Agreement will be effective only if in writing and signed by KADAMBA.
    <h2 class="font-bold">RELATIONSHIP BETWEEN THE PARTIES.</h2> This Agreement is not intended by the
    Parties to constitute or create a joint venture, pooling arrangement, partnership, agency or
    formal business organization of any kind. KADAMBA and the Alliance Partner/Business
    Partner shall be independent contractors with each other for all purposes at all times and neither
    Party shall act as or hold itself out as an agent or representative of the other Party nor shall
    create or attempt to create liabilities for the other Party by acting or holding itself out as such.
</div>
